version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    exclude:
      - deploy.sh  # ← this line avoids double copy
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ec2-user
